# Generated by Django 3.1.7 on 2021-04-25 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher', models.EmailField(max_length=254)),
                ('student', models.EmailField(max_length=254)),
                ('datetime', models.DateTimeField()),
            ],
        ),
    ]
